Repository breach-tw/breach.tw, pull requests merged in 2019-10, with the labels that each got.

#31 extract js into a single file
  js/main.js
  js/simplemde.min.js
  search.php
  search_step.php
  src/header.php
  subscribe.php
Labels: enhancement

#53 Clarify PGP key usage
  README.md
Labels: enhancement

#55 查詢訂閱+取消訂閱
  api/subscription_status.php
  api/unsubscribe.php
  js/main.js
  manage_subscription.php
  src/common.php
  src/header.php
  verify.php
Labels: enhancement, need more work

#61 偵測 IE 並建議使用現代瀏覽器
  ie.html
  js/detectIE.js
  robots.txt
  src/header.php
Labels: enhancement

#68 移除 type 欄位
  pages/source_item.vue
Labels: admin_panel, enhancement

#69 fix where statement error
  server/db.js
Labels: admin_panel, bug

#70 MAIL function
  config.json
  package-lock.json
  package.json
  server/api.js
  server/db.js
  server/email.html
  server/email.js
Labels: admin_panel, enhancement, need more work

#81 修正網站營運原則
  policy.php
Labels: enhancement

#80 整合訂閱頁面
  js/main.js
  manage_subscription.php
  src/header.php
  subscribe.php
Labels: enhancement

#36 C++ client
  .gitignore
  C++/compile_and_run.sh
  C++/index.cpp
  C++/src/httplib/httplib.h
  C++/src/sha1/sha1.cpp
  C++/src/sha1/sha1.h
Labels: client, need more work

#86 UI improvement
  faq.php
  js/main.js
  search.php
  search_step.php
  subscribe.php
Labels: enhancement

#98 Tag API
  server/api.js
  server/db.js
Labels: admin panel

#102 Windows C++ Client
  C++/compile_and_run.bat
  C++/index.cpp
Labels: client, enhancement
