Repository breach-tw/breach.tw, pull requests merged in 2019-08, with the labels that each got.

#14 Remove jQuery Dependency
  search.php
  search_step.php
  src/header.php
  subscribe.php
Labels: enhancement

#21 fix typo
  search.php
  subscribe.php
Labels: bug, typo

#23 python client
  python/index.py
  python/requirements.txt
Labels: client, enhancement, need more work

#22 node.js version example CLI
  .gitignore
  node.js/index.js
  node.js/package-lock.json
  node.js/package.json
Labels: client, enhancement, need more work
